# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_element: ignore
    deprecated_member_use: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # Disabled rules
    file_names: false
    unnecessary_underscores: false
    depend_on_referenced_packages: false
    avoid_print: false
