// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/categories/data/repositories/categories_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_flower_app/core/config/base_response/result.dart'
    as _i4;
import 'package:elevate_flower_app/features/categories/data/datasources/categories_remote_data_source_contract.dart'
    as _i2;
import 'package:elevate_flower_app/features/categories/data/models/category_model/category_response_model.dart'
    as _i5;
import 'package:elevate_flower_app/features/categories/data/models/product_model/products_response_models.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CategoriesRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesRemoteDataSourceContract extends _i1.Mock
    implements _i2.CategoriesRemoteDataSourceContract {
  MockCategoriesRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.CategoryResponseModel>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue:
                _i3.Future<_i4.Result<_i5.CategoryResponseModel>>.value(
                  _i6.dummyValue<_i4.Result<_i5.CategoryResponseModel>>(
                    this,
                    Invocation.method(#getAllCategories, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.CategoryResponseModel>>);

  @override
  _i3.Future<_i4.Result<_i7.ProductsResponseModels>> getAllProducts(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, [categoryId]),
            returnValue:
                _i3.Future<_i4.Result<_i7.ProductsResponseModels>>.value(
                  _i6.dummyValue<_i4.Result<_i7.ProductsResponseModels>>(
                    this,
                    Invocation.method(#getAllProducts, [categoryId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i7.ProductsResponseModels>>);
}
