// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/register/data/repositories/register_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:elevate_flower_app/core/config/base_response/result.dart'
    as _i6;
import 'package:elevate_flower_app/features/register/api/datasources/register_local_data_source_impl.dart'
    as _i3;
import 'package:elevate_flower_app/features/register/api/datasources/register_remote_data_source_impl.dart'
    as _i5;
import 'package:elevate_flower_app/features/register/data/models/register_request_body.dart'
    as _i8;
import 'package:elevate_flower_app/features/register/data/models/register_user_response_dto.dart'
    as _i7;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlutterSecureStorage_0 extends _i1.SmartFake
    implements _i2.FlutterSecureStorage {
  _FakeFlutterSecureStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterLocalDataSourceImpl extends _i1.Mock
    implements _i3.RegisterLocalDataSourceImpl {
  MockRegisterLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterSecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeFlutterSecureStorage_0(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i2.FlutterSecureStorage);

  @override
  set secureStorage(_i2.FlutterSecureStorage? value) => super.noSuchMethod(
    Invocation.setter(#secureStorage, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> saveAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAuthToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RegisterRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterRemoteDataSourceImpl extends _i1.Mock
    implements _i5.RegisterRemoteDataSourceImpl {
  MockRegisterRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.Result<_i7.RegisterUserResponseDto>> registerUser(
    _i8.RegisterRequestBody? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [user]),
            returnValue:
                _i4.Future<_i6.Result<_i7.RegisterUserResponseDto>>.value(
                  _i9.dummyValue<_i6.Result<_i7.RegisterUserResponseDto>>(
                    this,
                    Invocation.method(#registerUser, [user]),
                  ),
                ),
          )
          as _i4.Future<_i6.Result<_i7.RegisterUserResponseDto>>);
}
