// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/login/data/repositories/login_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:elevate_flower_app/core/config/base_response/result.dart'
    as _i7;
import 'package:elevate_flower_app/features/login/api/api_client/login_api_client.dart'
    as _i2;
import 'package:elevate_flower_app/features/login/api/datasources/login_local_data_source_impl.dart'
    as _i11;
import 'package:elevate_flower_app/features/login/api/datasources/login_remote_data_source_impl.dart'
    as _i5;
import 'package:elevate_flower_app/features/login/data/models/login_request_model.dart'
    as _i9;
import 'package:elevate_flower_app/features/login/data/models/login_response_model.dart'
    as _i8;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:shared_preferences/shared_preferences.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginApiClient_0 extends _i1.SmartFake
    implements _i2.LoginApiClient {
  _FakeLoginApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_1 extends _i1.SmartFake
    implements _i3.FlutterSecureStorage {
  _FakeFlutterSecureStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_2 extends _i1.SmartFake
    implements _i4.SharedPreferences {
  _FakeSharedPreferences_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRemoteDataSourceImpl extends _i1.Mock
    implements _i5.LoginRemoteDataSourceImpl {
  MockLoginRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeLoginApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.LoginApiClient);

  @override
  _i6.Future<_i7.Result<_i8.LoginResponseModel>> loginUser({
    required _i9.LoginRequestModel? body,
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [], {
              #body: body,
              #rememberMe: rememberMe,
            }),
            returnValue: _i6.Future<_i7.Result<_i8.LoginResponseModel>>.value(
              _i10.dummyValue<_i7.Result<_i8.LoginResponseModel>>(
                this,
                Invocation.method(#loginUser, [], {
                  #body: body,
                  #rememberMe: rememberMe,
                }),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i8.LoginResponseModel>>);
}

/// A class which mocks [LoginLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginLocalDataSourceImpl extends _i1.Mock
    implements _i11.LoginLocalDataSourceImpl {
  MockLoginLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FlutterSecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeFlutterSecureStorage_1(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i3.FlutterSecureStorage);

  @override
  _i4.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_2(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i4.SharedPreferences);

  @override
  _i6.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveRememberMe(bool? rememberMe) =>
      (super.noSuchMethod(
            Invocation.method(#saveRememberMe, [rememberMe]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearLoginData() =>
      (super.noSuchMethod(
            Invocation.method(#clearLoginData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
