// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/occasions/presentation/view_model/cubit/occasions_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_flower_app/core/config/base_response/result.dart'
    as _i4;
import 'package:elevate_flower_app/core/shared/entities/product_item_entity.dart'
    as _i8;
import 'package:elevate_flower_app/features/occasions/domain/entities/occasion_card_entity.dart'
    as _i5;
import 'package:elevate_flower_app/features/occasions/domain/use_cases/get_occasions_use_case.dart'
    as _i2;
import 'package:elevate_flower_app/features/occasions/domain/use_cases/get_products_by_occasion_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetOccasionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOccasionsUseCase extends _i1.Mock
    implements _i2.GetOccasionsUseCase {
  MockGetOccasionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.OccasionCardEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.OccasionCardEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.OccasionCardEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.OccasionCardEntity>>>);
}

/// A class which mocks [GetProductsByOccasionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsByOccasionUseCase extends _i1.Mock
    implements _i7.GetProductsByOccasionUseCase {
  MockGetProductsByOccasionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.ProductItemEntity>>> call(
    String? occasionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [occasionId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.ProductItemEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.ProductItemEntity>>>(
                    this,
                    Invocation.method(#call, [occasionId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.ProductItemEntity>>>);
}
