// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/register/presentation/view_model/cubit/register_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_flower_app/core/config/base_response/result.dart'
    as _i5;
import 'package:elevate_flower_app/features/register/domain/entities/register_params.dart'
    as _i7;
import 'package:elevate_flower_app/features/register/domain/entities/register_user_response.dart'
    as _i6;
import 'package:elevate_flower_app/features/register/domain/repositories/register_repository.dart'
    as _i2;
import 'package:elevate_flower_app/features/register/domain/use_cases/register_user_user_case.dart'
    as _i3;
import 'package:elevate_flower_app/features/register/domain/use_cases/save_token_use_case.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterRepository_0 extends _i1.SmartFake
    implements _i2.RegisterRepository {
  _FakeRegisterRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUserUseCase extends _i1.Mock
    implements _i3.RegisterUserUseCase {
  MockRegisterUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RegisterRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRegisterRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RegisterRepository);

  @override
  _i4.Future<_i5.Result<_i6.RegisterUserResponse>> call(
    _i7.RegisterParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.RegisterUserResponse>>.value(
              _i8.dummyValue<_i5.Result<_i6.RegisterUserResponse>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.RegisterUserResponse>>);
}

/// A class which mocks [SaveTokenUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTokenUseCase extends _i1.Mock implements _i9.SaveTokenUseCase {
  MockSaveTokenUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#call, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
