// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/register/api/datasources/register_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_flower_app/features/register/api/api_client/register_api_client.dart'
    as _i3;
import 'package:elevate_flower_app/features/register/data/models/register_request_body.dart'
    as _i5;
import 'package:elevate_flower_app/features/register/data/models/register_user_response_dto.dart'
    as _i2;
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterUserResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterUserResponseDto {
  _FakeRegisterUserResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterApiClient extends _i1.Mock implements _i3.RegisterApiClient {
  MockRegisterApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RegisterUserResponseDto> registerUser(
    _i5.RegisterRequestBody? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [body]),
            returnValue: _i4.Future<_i2.RegisterUserResponseDto>.value(
              _FakeRegisterUserResponseDto_0(
                this,
                Invocation.method(#registerUser, [body]),
              ),
            ),
          )
          as _i4.Future<_i2.RegisterUserResponseDto>);
}

/// A class which mocks [InternetConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnection extends _i1.Mock
    implements _i6.InternetConnection {
  MockInternetConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enableStrictCheck =>
      (super.noSuchMethod(
            Invocation.getter(#enableStrictCheck),
            returnValue: false,
          )
          as bool);

  @override
  Duration get checkInterval =>
      (super.noSuchMethod(
            Invocation.getter(#checkInterval),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#checkInterval),
            ),
          )
          as Duration);

  @override
  _i4.Future<bool> get hasInternetAccess =>
      (super.noSuchMethod(
            Invocation.getter(#hasInternetAccess),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i6.InternetStatus> get internetStatus =>
      (super.noSuchMethod(
            Invocation.getter(#internetStatus),
            returnValue: _i4.Future<_i6.InternetStatus>.value(
              _i6.InternetStatus.connected,
            ),
          )
          as _i4.Future<_i6.InternetStatus>);

  @override
  _i4.Stream<_i6.InternetStatus> get onStatusChange =>
      (super.noSuchMethod(
            Invocation.getter(#onStatusChange),
            returnValue: _i4.Stream<_i6.InternetStatus>.empty(),
          )
          as _i4.Stream<_i6.InternetStatus>);

  @override
  void setIntervalAndResetTimer(Duration? duration) => super.noSuchMethod(
    Invocation.method(#setIntervalAndResetTimer, [duration]),
    returnValueForMissingStub: null,
  );
}
