// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/forget-password/presentation/view_model/cubit/forget_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:elevate_flower_app/core/config/base_response/result.dart'
    as _i5;
import 'package:elevate_flower_app/features/forget_password/data/models/reset_password_dto/reset_password_dto.dart'
    as _i10;
import 'package:elevate_flower_app/features/forget_password/domain/entities/forget_password_entity/forget_password_entity.dart'
    as _i6;
import 'package:elevate_flower_app/features/forget_password/domain/repositories/forget_Password_repository.dart'
    as _i2;
import 'package:elevate_flower_app/features/forget_password/domain/use_cases/reset_password_use_case.dart'
    as _i9;
import 'package:elevate_flower_app/features/forget_password/domain/use_cases/send_otp_to_email_use_case.dart'
    as _i3;
import 'package:elevate_flower_app/features/forget_password/domain/use_cases/verify_otp_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForgetPasswordRepository_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordRepository {
  _FakeForgetPasswordRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SendOtpToEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendOtpToEmailUseCase extends _i1.Mock
    implements _i3.SendOtpToEmailUseCase {
  MockSendOtpToEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeForgetPasswordRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.ForgetPasswordRepository);

  @override
  _i4.Future<_i5.Result<_i6.ForgetPasswordEntity>> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i4.Future<_i5.Result<_i6.ForgetPasswordEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.ForgetPasswordEntity>>(
                this,
                Invocation.method(#call, [email]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.ForgetPasswordEntity>>);
}

/// A class which mocks [VerifyOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpUseCase extends _i1.Mock implements _i8.VerifyOtpUseCase {
  MockVerifyOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeForgetPasswordRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.ForgetPasswordRepository);

  @override
  _i4.Future<_i5.Result<void>> call(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#call, [code]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#call, [code]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i9.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeForgetPasswordRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.ForgetPasswordRepository);

  @override
  _i4.Future<_i5.Result<void>> call(_i10.ResetPasswordDTo? data) =>
      (super.noSuchMethod(
            Invocation.method(#call, [data]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#call, [data]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}
