// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_flower_app/test/features/best_seller/presentation/view_model/cubit/best_seller_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:elevate_flower_app/core/config/base_response/result.dart'
    as _i4;
import 'package:elevate_flower_app/features/best_seller/domain/entities/best_seller_page_entity.dart'
    as _i5;
import 'package:elevate_flower_app/features/best_seller/domain/use_cases/get_best_seller_products_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetBestSellerProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBestSellerProductsUseCase extends _i1.Mock
    implements _i2.GetBestSellerProductsUseCase {
  MockGetBestSellerProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.BestSellerPageEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Result<_i5.BestSellerPageEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.BestSellerPageEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.BestSellerPageEntity>>);
}
